const INITIAL_START_DATE = new Date('2022-07-01');
const INITIAL_END_DATE = new Date();
const INITIAL_CHART_INDEX = 0;
const INITIAL_ITEMS_PER_SLIDE = 7;
const options = [7, 15, 30];
const BAR_CHART_TITLE = 'Calories';
const AREA_CHART_TITLE = 'Workout Time';
const CHANGE_CHART_BTN_TITLE = 'Change Chart';
const NEXT_SLIDE_BTN_TITLE = 'next';
const PREV_SLIDE_BTN_TITLE = 'prev';

export {
  INITIAL_START_DATE,
  INITIAL_END_DATE,
  INITIAL_CHART_INDEX,
  INITIAL_ITEMS_PER_SLIDE,
  BAR_CHART_TITLE,
  AREA_CHART_TITLE,
  CHANGE_CHART_BTN_TITLE,
  NEXT_SLIDE_BTN_TITLE,
  PREV_SLIDE_BTN_TITLE,
  options
};
